### ISSUE TITLE
HttpClient simplification by using `ReschedulingOperation`

### ISSUE THREAD

**Issue by jentfoo** [threadly/litesockets-http#6]
The following logic to execute `RunSocket` task could be simplified by `ReschedulingOperation`:

https://github.com/threadly/litesockets-http/blob/master/client/src/main/java/org/threadly/litesockets/client/http/HTTPClient.java#L342-L344

Instead of needing to track the atomic boolean `RunSocket` could become a `ReschedulingOperation` and then we just invoke `.signalToRun()` when ever there is a queue item added.

**Comment by jentfoo** [comment]
Actually using `ReschedulingOperation` is needed to fix a race condition:

https://github.com/threadly/litesockets-http/blob/master/client/src/main/java/org/threadly/litesockets/client/http/HTTPClient.java#L441-L454

Once I realized it was an `AtomicBoolean` I realized that we could fall into the following condition:
* RunSocket has checked and the queue is empty, but has not entered final condition
* Code linked above checks boolean and sees nothing needed to run, so does not execute
* RunSocket now completes and sets the boolean back to false, without re-executing and leaving the item just idle in the queue for potentially forever

**Comment by lwahlmeier** [comment]
Yeah we should do another processQueue right after we set to false. Or we could refactor it the way you state above.  I really dont have any experience with ReschedulingOperation, so feel free too do that too.
